In [3]:
import pandas as pd
import numpy as np
df= pd.read_csv("./ObesityDataSet_raw_and_data_sinthetic.csv") # path
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [4]:
# binary categories to 0/1
from sklearn.preprocessing import LabelEncoder 
from numpy import array 

def bi_category(category):
    cate=array(category)
    encoder = LabelEncoder()
    cate_encoded =  encoder.fit_transform(cate) 
    category = cate_encoded
    return cate_encoded

df.Gender = bi_category(df.Gender)
df.family_history_with_overweight = bi_category(df.family_history_with_overweight)
df.FAVC = bi_category(df.FAVC)
df.SMOKE = bi_category(df.SMOKE)
df.SCC = bi_category(df.SCC)
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,21.0,1.62,64.0,1,0,2.0,3.0,Sometimes,0,2.0,0,0.0,1.0,no,Public_Transportation,Normal_Weight
1,0,21.0,1.52,56.0,1,0,3.0,3.0,Sometimes,1,3.0,1,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,1,23.0,1.80,77.0,1,0,2.0,3.0,Sometimes,0,2.0,0,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,1,27.0,1.80,87.0,0,0,3.0,3.0,Sometimes,0,2.0,0,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,1,22.0,1.78,89.8,0,0,2.0,1.0,Sometimes,0,2.0,0,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [5]:
# frequency categories
def freq_category(s):
    df.loc[df[s] == "no", s] = 0
    df.loc[df[s] == "Sometimes", s] = 1
    df.loc[df[s] == "Frequently", s] = 2
    df.loc[df[s] == "Always", s] = 3
freq_category('CAEC')
freq_category('CALC')
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,21.0,1.62,64.0,1,0,2.0,3.0,1,0,2.0,0,0.0,1.0,0,Public_Transportation,Normal_Weight
1,0,21.0,1.52,56.0,1,0,3.0,3.0,1,1,3.0,1,3.0,0.0,1,Public_Transportation,Normal_Weight
2,1,23.0,1.80,77.0,1,0,2.0,3.0,1,0,2.0,0,2.0,1.0,2,Public_Transportation,Normal_Weight
3,1,27.0,1.80,87.0,0,0,3.0,3.0,1,0,2.0,0,2.0,0.0,2,Walking,Overweight_Level_I
4,1,22.0,1.78,89.8,0,0,2.0,1.0,1,0,2.0,0,0.0,0.0,1,Public_Transportation,Overweight_Level_II

In [6]:
# MTRANS and label 
df.loc[df["MTRANS"] == "Automobile", "MTRANS"] = 0
df.loc[df["MTRANS"] == "Motorbike", "MTRANS"] = 1
df.loc[df["MTRANS"] == "Public_Transportation", "MTRANS"] = 2
df.loc[df["MTRANS"] == "Bike", "MTRANS"] = 3
df.loc[df["MTRANS"] == "Walking", "MTRANS"] = 4

df.loc[df["NObeyesdad"] == "Insufficient_Weight", "NObeyesdad"] = 0
df.loc[df["NObeyesdad"] == "Normal_Weight", "NObeyesdad"] = 1
df.loc[df["NObeyesdad"] == "Overweight_Level_I", "NObeyesdad"] = 2
df.loc[df["NObeyesdad"] == "Overweight_Level_II", "NObeyesdad"] = 3
df.loc[df["NObeyesdad"] == "Overweight_Level_III", "NObeyesdad"] = 4
df.loc[df["NObeyesdad"] == "Obesity_Type_I", "NObeyesdad"] = 5
df.loc[df["NObeyesdad"] == "Obesity_Type_II", "NObeyesdad"] = 6
df.loc[df["NObeyesdad"] == "Obesity_Type_III", "NObeyesdad"] = 7
df.head(74)

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,0,21.0,1.62,64.0,1,0,2.0,3.0,1,0,2.0,0,0.0,1.0,0,2,1
1,0,21.0,1.52,56.0,1,0,3.0,3.0,1,1,3.0,1,3.0,0.0,1,2,1
2,1,23.0,1.80,77.0,1,0,2.0,3.0,1,0,2.0,0,2.0,1.0,2,2,1
3,1,27.0,1.80,87.0,0,0,3.0,3.0,1,0,2.0,0,2.0,0.0,2,4,2
4,1,22.0,1.78,89.8,0,0,2.0,1.0,1,0,2.0,0,0.0,0.0,1,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,1,23.0,1.80,60.0,1,0,2.0,3.0,0,0,3.0,0,0.0,1.0,1,2,1
70,0,23.0,1.65,80.0,1,1,2.0,3.0,3,0,2.0,0,0.0,2.0,0,2,3
71,0,22.0,1.67,50.0,1,0,3.0,3.0,0,0,3.0,1,2.0,1.0,1,2,0
72,0,24.0,1.65,60.0,1,0,2.0,3.0,1,0,3.0,1,1.0,0.0,0,2,1
73,1,19.0,1.85,65.0,1,0,2.0,3.0,1,0,3.0,0,2.0,1.0,1,3,1

In [7]:
# check if all categorical data are numerical now - returns 0 means yes
np.argmin(df.applymap(np.isreal).all(1))

0

In [11]:
# normalization
label = df.NObeyesdad
df = df.drop(columns=["NObeyesdad"])
df = (df-df.min())/(df.max()-df.min())
df["NObeyesdad"] = label
print(df.head())
df.to_csv('Processed_data.csv',index = False)

  Gender       Age    Height    Weight family_history_with_overweight FAVC  \
0    0.0  0.148936  0.320755  0.186567                            1.0  0.0
1    0.0  0.148936  0.132075  0.126866                            1.0  0.0
2    1.0  0.191489  0.660377  0.283582                            1.0  0.0
3    1.0  0.276596  0.660377  0.358209                            0.0  0.0
4    1.0  0.170213  0.622642  0.379104                            0.0  0.0

  FCVC       NCP      CAEC SMOKE CH2O  SCC       FAF  TUE      CALC MTRANS  \
0  0.5  0.666667  0.333333   0.0  0.5  0.0       0.0  0.5       0.0    0.5
1  1.0  0.666667  0.333333   1.0  1.0  1.0       1.0  0.0  0.333333    0.5
2  0.5  0.666667  0.333333   0.0  0.5  0.0  0.666667  0.5  0.666667    0.5
3  1.0  0.666667  0.333333   0.0  0.5  0.0  0.666667  0.0  0.666667    1.0
4  0.5       0.0  0.333333   0.0  0.5  0.0       0.0  0.0  0.333333    0.5

  NObeyesdad
0          1
1          1
2          1
3          2
4          3